name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [22.1, 23.0]
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.1
        with:
          otp-version: ${{matrix.otp}}
      - run: rebar3 do eunit,ct,dialyzer
